### ISSUE TITLE
Decode tracks not working

### ISSUE THREAD

**Issue by karelkryda** [MenuDocs/erela.js#100]
Decode tracks function not working, because it must be POST function

I repaired it in my 3 PRs, check:
https://github.com/MenuDocs/erela.js/pull/97

**Comment by acollierr17** [comment]
Can you provide logs or screenshots? The exact steps you followed to reproduce this issue? That would help a lot.

**Comment by karelkryda** [comment]
@acollierr17 https://github.com/MenuDocs/erela.js/pull/101 what should I change...I literally hate TypeScript...

And https://cdn.discordapp.com/attachments/804459883017142272/827572653140475924/unknown.png

**Comment by acollierr17** [comment]
Thank you. I was able to reproduce the steps.

Steps to reproduce:

1. Get a base64 encoded track string (example below)
2. Use the `Manager#decodeTracks` method to decode that string (parameter accepts `string[]`)
3. The result from the `Manager#decodeTracks` method should return a JSON object representing a `405` error saying the `GET` method is not allowed

Error.
![usVhZgd](https://user-images.githubusercontent.com/16583889/113492623-ae9def00-94a6-11eb-96fc-33820ea4a810.png)

Code example.

**Comment by karelkryda** [comment]
@acollierr17 yes, that's it 👍
