### ISSUE TITLE
Nothing is playing.

### ISSUE THREAD

**Issue by JustinnnDev** [MenuDocs/erela.js#103]
So, i've been checking this out for a while right now and thought about copying the stuff in "examples" (so index + commands), and did everything, (installing Lavalink and stuff).

But for a surprise as me, everything works (the commands and stuff) and if I start (!play ncs limitless &example <-) the bot joins the voice channel, but it does not start playing at all.

Is that a issue or? #

**Comment by JustinnnDev** [comment]
I have tried everything at this point, I have uninstalled and reinstalled erela.js, but unfortunately still the same result (I am using Node.js V14 + Java 13)

I even created a new discord bot with the "Administrator" permission, but still nothing starts playing.

**Comment by karelkryda** [comment]
no song may have been found

**Comment by JustinnnDev** [comment]
what do you mean? I just copied the entire thing of the "examples" folder of the code here.

**Comment by karelkryda** [comment]
u should have
```
case "NO_MATCHES":
case "LOAD_FAILED":
   return message.channel.send("something went wrong")
```

try this

**Comment by JustinnnDev** [comment]
in my play.js?

**Comment by karelkryda** [comment]
yes, there is already `case "NO_MATCHES":` so just add `case "LOAD_FAILED":`

**Comment by JustinnnDev** [comment]
I already have it, and it was in the example code aswell (I just copied that)
[code](https://i.imgur.com/qAbaqEA.png)
[discord result](https://i.imgur.com/C9Tu6y7.png)

**Comment by karelkryda** [comment]
ok, can you send whole code? just to be sure it's ok

**Comment by JustinnnDev** [comment]
yea here, https://sourceb.in/NpC9yT5msi
again it's literary the same code from https://github.com/MenuDocs/erela.js/blob/master/examples/commands/play.js

**Comment by karelkryda** [comment]
code looks normal. can you send lavalink log?

**Comment by JustinnnDev** [comment]
yea, https://paste.gg/p/anonymous/174f8c53f62e435ab2fe78babcf74f64

**Comment by karelkryda** [comment]
update to Lavalink 3.3.2.4

https://github.com/Frederikam/Lavalink/releases/download/3.3.2.4/Lavalink.jar

**Comment by JustinnnDev** [comment]
Aha. Got it fixed & working again ^ Thanks for the help :)
