### ISSUE TITLE
Bot doesnt connect after undeaf/deaf while playing.

### ISSUE THREAD

**Issue by KasaiKonoru** [MenuDocs/erela.js#108]
Pls I need help.
If someone change the region of the voice channel or deaf/undeaf or servermute my bot while playing music, the bot stops playing music but stays in the channel. But in nowplaying (cmd) I can see the bot still plays the current track. 

I can hear anything again if someone joins the voice channel or if I skip the track.

What I must chnage in the code? How could I solve this?

**Comment by Anish-Shobith** [comment]
Hello there its not possible for us to help you without , please provide code which can help us understand this issue! A code which can reproduce your error ! Or else please use our discord to get help! https:discord.gg/menudocs

**Comment by RedfurREBORN** [comment]
Ok well this is because your bot is streaming to a non existent channel. You can fix this by resetting the channel again. There should be a discord event that checks if the voice region changed. Over there set the voice channel again or just play the current track again in the same position.
