### ISSUE TITLE
"Provided Argument must be present"

### ISSUE THREAD

**Issue by Ronak0020** [MenuDocs/erela.js#109]
Hello there,
I am trying to use Lavalink for music in my discord bot. I followed the guide from the website but I am getting this error whenever I search for any music :

``` Node localhost connected
[]
D:\Cronaium\node_modules\erela.js\dist\structures\Utils.js:46
            throw new RangeError("Provided argument must be present.");
                  ^

RangeError: Provided argument must be present.
    at Function.validate (D:\Cronaium\node_modules\erela.js\dist\structures\Utils.js:46:19)
    at Queue.add (D:\Cronaium\node_modules\erela.js\dist\structures\Queue.js:38:33)
    at Object.run (D:\Cronaium\commands\Music\play.js:16:22)
```

![image](https://user-images.githubusercontent.com/49647021/115814790-971d9c00-a3aa-11eb-8cfa-0a4d9c008b37.png)

I have java version 15.

**Comment by Gabb-c** [comment]
Hey!

Lavalink doesn't work pretty great with Java 15. You should try Java 13.

![image](https://user-images.githubusercontent.com/65926741/115818082-62253f80-a3d2-11eb-80dd-b5af4e90f83f.png)

**Comment by melike2d** [comment]
> Hey!
> 
> Lavalink doesn't work pretty great with Java 15. You should try Java 13.
> 
> ![image](https://user-images.githubusercontent.com/65926741/115818082-62253f80-a3d2-11eb-80dd-b5af4e90f83f.png)

what... this has nothing to do with Java? 
The error is from erela itself

**Comment by Ronak0020** [comment]
> > Hey!
> > Lavalink doesn't work pretty great with Java 15. You should try Java 13.
> > ![image](https://user-images.githubusercontent.com/65926741/115818082-62253f80-a3d2-11eb-80dd-b5af4e90f83f.png)
> 
> what... this has nothing to do with Java?
> The error is from erela itself

exactly. That's what I've been wondering. Lavalink is working fine. It launches and runs properly~
The error says there is a problem in erela.js ig

**Comment by Gabb-c** [comment]
@melike2d, guess you're right. I've misread the issue (sry it's almost 3 am in Brazil hehe).

So @Ronak0020, where are u getting this error? Reading the error, It looks like you're passing `null` or `undefined` to some function.

**Comment by melike2d** [comment]
@Ronak0020 what search plugins do you have installed?

**Comment by Ronak0020** [comment]
@Gabb-c in Line number 16-
![image](https://user-images.githubusercontent.com/49647021/115824495-dc4ac980-a3bc-11eb-96e0-5e07dcf5d36f.png)

**Comment by Ronak0020** [comment]
> @Ronak0020 what search plugins do you have installed?

I have not installed any search plugins ._.
For music, I only have Lavalinks.jar, application.yml, erela.js
and I tried to make it work at first by just copying the codes of the guide. Without adding something extra by my side

**Comment by Gabb-c** [comment]
> @Gabb-c in Line number 16-
> ![image](https://user-images.githubusercontent.com/49647021/115824495-dc4ac980-a3bc-11eb-96e0-5e07dcf5d36f.png)

Ok, that's how I'm playing music in my bot:

![image](https://user-images.githubusercontent.com/65926741/115825794-4fb20280-a3e0-11eb-8d9e-40b9511b843f.png)

![image](https://user-images.githubusercontent.com/65926741/115825733-3b6e0580-a3e0-11eb-9fff-37c3a285b1a0.png)

The variable `choice` is the track.

When you console.log the res.tracks, are u getting the tracks?
And what do you get in the message.content.slice(7) ?

**Comment by Ronak0020** [comment]
nope when I log the tracks, I get an empty array
The issue is with searching for music...

**Comment by Gabb-c** [comment]
When I pass an empty string to one of the arguments, the response is:

```js
{ loadType: 'NO_MATCHES', exception: null, tracks: [] }
```

**Comment by Ronak0020** [comment]
This is what I receive in the Lavalink log when I search for music ->
![image](https://user-images.githubusercontent.com/49647021/115829168-7dd51980-a3c3-11eb-8abe-34599524501e.png)

And this is what it logs in bot terminal ->
![image](https://user-images.githubusercontent.com/49647021/115829452-e02e1a00-a3c3-11eb-9685-51fe1a7f51fb.png)

**Comment by Ronak0020** [comment]
> This is the code I have written ->
First, a different `manager.js` file for this one
![image](https://user-images.githubusercontent.com/49647021/115829716-26837900-a3c4-11eb-83f2-5967daa4e4d1.png)

in `ready.js` event ->
![image](https://user-images.githubusercontent.com/49647021/115829771-38651c00-a3c4-11eb-9f17-6ec4f0576e78.png)

`index.js` file
![image](https://user-images.githubusercontent.com/49647021/115829844-503ca000-a3c4-11eb-82cb-5b6936eb05c1.png)
![image](https://user-images.githubusercontent.com/49647021/115829868-592d7180-a3c4-11eb-887b-5be7377e1eb0.png)

And lastly, `play.js` file
![image](https://user-images.githubusercontent.com/49647021/115829915-6ba7ab00-a3c4-11eb-93ab-93ca29f6fee0.png)


### This is the complete music code in my bot using Lavalink and erela~

**Comment by Ronak0020** [comment]
I finally fixed it~
The same thing was working on my VPS. I just tried re-installing Java and downloading Lavalink again and it worked in my local computer as well
