### ISSUE TITLE
Issues after using the Disconnect Feature of discord to kick the bot while playing music.

### ISSUE THREAD

**Issue by RifksSch** [MenuDocs/erela.js#110]
If u use discord disconnect feature while it's playing music.
then if u request another song right after
You have to wait for a couple of minutes
And it might also make the bot not joining the VC.

how would I fix this issue?

**Comment by Gabb-c** [comment]
Still trying to fix it, but guess you could use the [playerMove](https://solaris.codes/projects/erelajs/docs/classes/Manager.html#playermove) event.

**Comment by RifksSch** [comment]
@Gabb-c Any ETA on when this will be fixed?
