### ISSUE TITLE
(node:4051) UnhandledPromiseRejectionWarning: Error: No available nodes.

### ISSUE THREAD

**Issue by KrabbyBuckets** [MenuDocs/erela.js#112]
i dont know why but it throws this error.

**Comment by karelkryda** [comment]
that means u have no Lavalink nodes connected

**Comment by KrabbyBuckets** [comment]
@karelkryda but i ran java -jar Lavalink.jar in another terminal. so it should be running.

**Comment by KrabbyBuckets** [comment]
i got it. i forgot <Manager>.init(). my bad
