### ISSUE TITLE
Volume increase itself

### ISSUE THREAD

**Issue by soudblox** [MenuDocs/erela.js#113]
When a song is playing, then i run a code that adds another song to the queue, the volume of the song suddenly increase for a few second, and then the volume goes back to normal, is that normal?

**Comment by soudblox** [comment]
Used the same code in https://solaris.codes/projects/erelajs/guides/basics.html#first-start

**Comment by Anish-Shobith** [comment]
Are you sure its erela.js ? and not the song itself ? Can you debug or check lavalink logs if volume has changed or maybe even check using the bot if volume has changed.

**Comment by soudblox** [comment]
i thought i already closed this issue, i already solved it, the player connect again even though it's already connected, fixed by adding `if (player.state !== "CONNECTED") player.connect()`
