### ISSUE TITLE
Some tracks do not start playing

### ISSUE THREAD

**Issue by NotReallyEight** [MenuDocs/erela.js#119]
I noticed that while playing playlists/YouTube mixes (didn't try with Spotify playlists yet), the `trackStart` event gets fired but then skips the current track and starts the next track.
Look at this image for reference (can't find a more clear one but I hope it is understandable): https://media.discordapp.net/attachments/768481503805964341/855729848018665482/Screenshot_20210619-104333_Discord-Beta.jpg

**Comment by Solaris9** [comment]
Add the trackError and trackStuck event and see if it emits either

**Comment by NotReallyEight** [comment]
_Forgot to say that this happens only sometimes and not everytime that I play a playlist_

**Comment by NotReallyEight** [comment]
> Add the trackError and trackStuck event and see if it emits either

Ok

**Comment by NotReallyEight** [comment]
Ok, some more news. After testing it these are the errors from the trackStuck/trackError event:
![image](https://user-images.githubusercontent.com/71493060/122651295-2db2d300-d138-11eb-82ba-a00fcbc81b5e.png)

**Comment by Solaris9** [comment]
Then Lavalink had issues playing the track, nothing you can fix other than letting the user know and tell them to play another version of that song.

**Comment by NotReallyEight** [comment]
Hmm sometimes it just spams the trackStart message so ehh thar was the reason why I was wondering. Any kind of "fix" to not let it send the message that comes with the trackStart event once getting fired? as it just spams a lot haha

**Comment by Solaris9** [comment]
Send the track start message after like 5 second if the track error doesn't emit, so you'd need to use player data to say whether a error or not and after 5 seconds send the playing message

**Comment by NotReallyEight** [comment]
Ohhh ok. Thanks for help 👍

**Comment by NotReallyEight** [comment]
Hey, so I was working on it today. What kind of player data I actually need to see if it's an error or not?

**Comment by Tomato6966** [comment]
use a different java version and ip routing also check lavalink issues

**Comment by Moquent** [comment]
> Hey, so I was working on it today. What kind of player data I actually need to see if it's an error or not?

Just console.log the error events with manager#on("trackError", ()=>{}) and if they are track breaking events then its probably a 403 unauthorized error which you can't do anything about. I suggest you use multiple nodes to reduce the chances of this happening, and don't forget to add an identifier for each node in the array.

**Comment by dragonfirefox** [comment]
> Ok, some more news. After testing it these are the errors from the trackStuck/trackError event: ![image](https://user-images.githubusercontent.com/71493060/122651295-2db2d300-d138-11eb-82ba-a00fcbc81b5e.png) It started spamming those errors after a while btw

Some of tracks probably age restricted or somewhat. Also use IP routing and if you're using any free public lavalink servers try avoiding them.

**Comment by dragonfirefox** [comment]
Can you provide which track of tracks causing this issue?

**Comment by NotReallyEight** [comment]
Oh forgot to close this issue as that bot has been shut down by me personally.
