### ISSUE TITLE
Docs are gone.

### ISSUE THREAD

**Issue by Luna-devv** [MenuDocs/erela.js#121]
Hey,
I would like to ask where the docs are now, because the [linked docs](https://solaris.codes/projects/erelajs/docs/gettingstarted.html) leads to a 404 page.

Screenshot:  https://cdn.xyna.space/krp62knwg9a

**Comment by joeyk710** [comment]
yeah i asked in their discord and they said its temporarily down. use the github repo as documentation for now until the website is back online. i would highly suggest you join their discord server for more info and help
