### ISSUE TITLE
Docs are goon again.

### ISSUE THREAD

**Issue by Luna-devv** [MenuDocs/erela.js#122]
Hey,
I would like to ask where the docs are now, because the [linked docs](http://solaris.codes/projects/erelajs/docs/gettingstarted.html) leads to a namecheap page.

Screenshot: https://cdn.xyna.space/ks6j0u0si9a

**Comment by Solaris9** [comment]
my domain expired but docs will be on it's own site sometime, for now you can use the netlify url https://solaris-site.netlify.app/
