### ISSUE TITLE
Unable to connect after 5 attempts.

### ISSUE THREAD

**Issue by skibop** [MenuDocs/erela.js#125]
When trying to connect to a lavalink server, after a certain while it will simply just output the message of, Node "lava.link" encountered an error: Unable to connect after 5 attempts..

I'm not sure how to fix this, if anyone can help out that would be appreciated.

**Comment by melike2d** [comment]
You probably supplied incorrect details, double check the supplied host, port, and password.

**Comment by skibop** [comment]
All of them seem to be correct

**Comment by melike2d** [comment]
Could you send a screenshot of your lavalink logs, make sure to blur out any IPs

**Comment by skibop** [comment]
What's happening is that at first they connect, then after some time the node reconnects and reconnects until I get that error message

**Comment by skibop** [comment]
Actually, im using a shared lavalink server between people which is public

**Comment by melike2d** [comment]
> Actually, im using a shared lavalink server between people which is public

If you can't supply any logs then I doubt we'll be able to help you, best advice i can give you is host your own lavalink instance.

**Comment by skibop** [comment]
Oh ok, thank you

**Comment by skibop** [comment]
Fixed the issue, the company I was taking the lavalink from, had an issue and they fixed it. Thank you for the fast support regardless.
