### ISSUE TITLE
Issue with audio cutting off

### ISSUE THREAD

**Issue by SuperSweatyTejas** [MenuDocs/erela.js#128]
Hi im having an issue with the audio cutting off within a few seconds when playback starts for example

Music plays for a couple of seconds but then cuts off, the queue is still active and I can add songs destroy etc.

**Comment by melike2d** [comment]
erela.js doesn't handle playback of tracks. If anything this is an issue with your lavalink node, whether it be a slow cpu or low memory.

**Comment by SuperSweatyTejas** [comment]
i see thanks, i thought it was an issue with the lavalink just wanted to make sure
