### ISSUE TITLE
Support for the Discordoo?

### ISSUE THREAD

**Issue by Pelfox** [MenuDocs/erela.js#129]
Hi! Now very smart people developing new Discord library for the Node.js - [Discordoo](https://github.com/Discordoo/discordoo). Will `erela.js` support it?
Thanks for the response.

**Comment by Anish-Shobith** [comment]
Doesn't matter what discord api library you use of (node.js) as long you send the packets properly it doesn't matter if you are using eris, djs or discordoo.

**Comment by Pelfox** [comment]
> Doesn't matter what discord api library you use of (node.js) as long you send the packets properly it doesn't matter if you are using eris, djs or discordoo.

Oh, okay, thanks! It's pretty good. Thanks for this library, it's really fast & usable in the production. Good luck :)
