### ISSUE TITLE
Received session description before protocol selection

### ISSUE THREAD

**Issue by SuperSweatyTejas** [MenuDocs/erela.js#134]
Getting this in the logs WARN 27 --- [ntLoopGroup-2-2] m.k.k.gateway.VoiceGatewayV4Connection : Received session description before protocol selection? (connection id = .....)  

Audio plays for a few seconds then cuts out

tried asking on https://github.com/KyokoBot/koe 

got this as a response: https://github.com/KyokoBot/koe/issues/16

Is there a way I can implement the fix they suggested

**Comment by melike2d** [comment]
The fix they suggested cannot be done in a client (or in lavalink) as it's code specifically within Koe

**Comment by SuperSweatyTejas** [comment]
Then what would you suggest the fix would be?

**Comment by melike2d** [comment]
Discord bug
