### ISSUE TITLE
Erela.js breaks voiceStateUpdate of bot itself

### ISSUE THREAD

**Issue by topjor** [MenuDocs/erela.js#136]
When a player is active, erela.js breaks the `voiceStateUpdate` `newState` from discord.js.
when a bot is force disconnected by an admin, the `newState.channel` gets messed up and set to the same value as the `oldState` even though being disconnected.
when using a secondary instance of the bot where no player is active, the observed `newState` is correct but on the instance where the player is active, the `newState` gets messed with and is somehow set to the same value as the `oldValue`.

**Comment by RoDaBaFilms** [comment]
Perhaps an issue in https://github.com/MenuDocs/erela.js/blob/819bdcd05dcac33941c1b5f1db4b421a00502056/src/structures/Manager.ts#L474 as the actual packet is being mutated.

**Comment by topjor** [comment]
jep thats the issue!

**Comment by melike2d** [comment]
Fixed by #142?

**Comment by melike2d** [comment]
closed in favor of #145
