### ISSUE TITLE
discord.js v13 not working

### ISSUE THREAD

**Issue by WhiteSinner0** [MenuDocs/erela.js#152]
erela.js - 2.3.3
discord.js - 13/12

Good afternoon, there is a problem with erela.js.
When using Discord.js v13 bot connects to the voice channel, but does not play, although if you ask the status of the player it plays. But when using discord.js v12 everything works as it should. I need to use discord.js v13.

discord.js v12 code: 
```js
const { Client } = require("discord.js");
const { Manager } = require("erela.js");

const client = new Client();

client.manager = new Manager({
  nodes:[{host: "",port: 2333,password: ""}],
  send(id, payload) {
    const guild = client.guilds.cache.get(id);
    if (guild) guild.shard.send(payload);
  },
}).on("nodeConnect", node => console.log(`Node ${node.options.identifier} connected`))

client.once("ready", () => {
  console.log("I am ready!");
  client.manager.init(client.user.id);
});

client.on("raw", (d) => client.manager.updateVoiceState(d));

client.on("message", async (message) => {
  if (message.content.startsWith("!play")) {
    const res = await client.manager.search(
        'Lofi Hip Hop.',
        ''
      );
      const player = client.manager.create({
        guild: '',
        voiceChannel: '',
        textChannel: '',
      });
      player.connect();
      player.queue.add(res.tracks[0]);
      if (!player.playing && !player.paused && !player.queue.size)player.play();
  }
});

client.login('');
```

discord.js v13 code: 
```js
const { Client, Intents } = require('discord.js');
const { Manager } = require("erela.js");
const client = new Client({ intents: [Intents.FLAGS.GUILDS] });
client.manager = new Manager({
  nodes:[{host: "",port:2333,password: ""}],
  send(id, payload) {
    const guild = client.guilds.cache.get(id);
    if (guild) guild.shard.send(payload);
  },
}).on("nodeConnect", node => console.log(`Node ${node.options.identifier} connected`))

client.on('ready', () => {
    console.log(`I am ready!`);
    client.manager.init('');
});

client.on('interactionCreate', async interaction => {
  if (!interaction.isCommand()) return;

  if (interaction.commandName === 'test') {
    const res = await client.manager.search(
      'Lofi Hip Hop.',
      ''
    );
    const player = client.manager.create({
      guild: '',
      voiceChannel: '',
      textChannel: '',
    });
    player.connect();
    player.queue.add(res.tracks[0]);
    if (!player.playing && !player.paused && !player.queue.size)player.play();
  }
});

client.login('');
```

**Comment by CustomTag** [comment]
Make sure you have Intents.FLAGS.GUILD_VOICE_STATES in your Client Options

**Comment by CustomTag** [comment]
Like this const client = new Client({ intents: [ Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_VOICE_STATES] });

**Comment by WhiteSinner0** [comment]
nothing has changed. :(

**Comment by CustomTag** [comment]
What do you get for error?

**Comment by CustomTag** [comment]
wait

**Comment by CustomTag** [comment]
i see what your problem is 2 sec

**Comment by CustomTag** [comment]
const { Client, Intents } = require('discord.js');
const { Manager } = require("erela.js");
const client = new Client({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_VOICE_STATES] });
client.manager = new Manager({
nodes:[{host: "",port:2333, password: ""}],
send(id, payload) {
const guild = client.guilds.cache.get(id);
if (guild) guild.shard.send(payload);
},
}).on("nodeConnect", node => console.log(Node ${node.options.identifier} connected))

client.on('ready', () => {
console.log(I am ready!);
client.manager.init(client.user.id);
});

client.on('interactionCreate', async interaction => {
if (!interaction.isCommand()) return;

if (interaction.commandName === 'test') {
const res = await client.manager.search(
'Lofi Hip Hop.',
''
);
const player = client.manager.create({
guild: interaction.guild.id,
voiceChannel: interaction.member.voice.channel.id,
textChannel: interaction.channel.id,
});
player.connect();
player.queue.add(res.tracks[0]);
if (!player.playing && !player.paused && !player.queue.size)player.play();
}
});

client.login('');

**Comment by CustomTag** [comment]
Try that

**Comment by WhiteSinner0** [comment]
nothing has changed. :(

**Comment by CustomTag** [comment]
do you have lavalink? server

**Comment by WhiteSinner0** [comment]
Yes

**Comment by CustomTag** [comment]
Well idk try look over your code and see if you have errors or something

**Comment by WhiteSinner0** [comment]
There are no errors in either the Lavalink or the script.

**Comment by WhiteSinner0** [comment]
Lavalink: 
2021-12-20 15:13:18.633  INFO 27 --- [  XNIO-1 task-9] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:4959
2021-12-20 15:13:18.691  INFO 27 --- [  XNIO-1 task-9] lavalink.server.io.SocketServer          : Connection successfully established from erela.js
2021-12-20 15:13:21.378  INFO 27 --- [ XNIO-1 task-10] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:Lofi Hip Hop."
2021-12-20 15:13:22.167  INFO 27 --- [ader-2-thread-4] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: Lofi Hip Hop.
2021-12-20 15:13:22.241  INFO 27 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"volume","guildId":"","volume":100}
2021-12-20 15:13:22.242  INFO 27 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"play","guildId":"","track":"QAAAmgIANzEgQS5NIFN0dWR5IFNlc3Npb24g7aC97bOaIC0gW2xvZmkgaGlwIGhvcC9jaGlsbCBiZWF0c10ACUxvZmkgR2lybAAAAAAAOA+QAAtsVFJpdUZJV1Y1NAABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PWxUUml1RklXVjU0AAd5b3V0dWJlAAAAAAAAAAA="}

**Comment by itzJOHv** [comment]
> Lavalink: 2021-12-20 15:13:18.633 INFO 27 --- [ XNIO-1 task-9] l.server.io.HandshakeInterceptorImpl : Incoming connection from /127.0.0.1:4959 2021-12-20 15:13:18.691 INFO 27 --- [ XNIO-1 task-9] lavalink.server.io.SocketServer : Connection successfully established from erela.js 2021-12-20 15:13:21.378 INFO 27 --- [ XNIO-1 task-10] l.server.player.AudioLoaderRestHandler : Got request to load for identifier "ytsearch:Lofi Hip Hop." 2021-12-20 15:13:22.167 INFO 27 --- [ader-2-thread-4] lavalink.server.player.AudioLoader : Loaded playlist Search results for: Lofi Hip Hop. 2021-12-20 15:13:22.241 INFO 27 --- [ XNIO-1 I/O-2] lavalink.server.io.SocketServer : {"op":"volume","guildId":"","volume":100} 2021-12-20 15:13:22.242 INFO 27 --- [ XNIO-1 I/O-2] lavalink.server.io.SocketServer : {"op":"play","guildId":"","track":"QAAAmgIANzEgQS5NIFN0dWR5IFNlc3Npb24g7aC97bOaIC0gW2xvZmkgaGlwIGhvcC9jaGlsbCBiZWF0c10ACUxvZmkgR2lybAAAAAAAOA+QAAtsVFJpdUZJV1Y1NAABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PWxUUml1RklXVjU0AAd5b3V0dWJlAAAAAAAAAAA="}

guildId is empty?

**Comment by WhiteSinner0** [comment]
no

**Comment by dragonfirefox** [comment]
> ```js
> const { Client, Intents } = require('discord.js');
> const { Manager } = require("erela.js");
> const client = new Client({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_VOICE_STATES] });
> client.manager = new Manager({
> nodes:[{host: "",port:2333, password: ""}],
> send(id, payload) {
> const guild = client.guilds.cache.get(id);
> if (guild) guild.shard.send(payload);
> },
> }).on("nodeConnect", node => console.log(Node ${node.options.identifier} connected))
> 
> client.on('ready', () => {
> console.log(I am ready!);
> client.manager.init(client.user.id);
> });
> 
> client.on('interactionCreate', async interaction => {
> if (!interaction.isCommand()) return;
> 
> if (interaction.commandName === 'test') {
> const res = await client.manager.search(
> 'Lofi Hip Hop.',
> ''
> );
> const player = client.manager.create({
> guild: interaction.guild.id,
> voiceChannel: interaction.member.voice.channel.id,
> textChannel: interaction.channel.id,
> });
> player.connect();
> player.queue.add(res.tracks[0]);
> if (!player.playing && !player.paused && !player.queue.size)player.play();
> }
> });
> 
> client.login('');
> ```

Hey, you've not specified `raw` event. In raw the voice packets are served to voice channel.
That's what you missed and also @WhiteSinner0 missed in v13 `<Client>.on("raw", (d) => client.manager.updateVoiceState(d));`.

Also noticed that @WhiteSinner0 you've not specified intents, guildID on your v13 code or even done haven't specified in this issue.

https://github.com/MenuDocs/erela.js/issues/152#issuecomment-997962752
If you haven't specified guildid it wouldn't fireup on that guild on which you want, I saw your logs doesn't contains guildId string.

**Comment by WhiteSinner0** [comment]
Thanks for the answer! Everything works great now :)
