### ISSUE TITLE
Please add "guild.voice.connection"

### ISSUE THREAD

**Issue by AndreP2211** [MenuDocs/erela.js#154]
Please utilize guild.voice.connection, that would be realy helpfull when working with other functions for a bot beside music playing.
At the moment I need no make 2 bots working together because I cant get the "guild.voice.connection" with my Music bot.
Thanks for reading and a happy new Year.

**Comment by melike2d** [comment]
Erela.js is a generic library, meaning it is independent of specific Discord API wrappers/libraries.
