### ISSUE TITLE
trackStart event gets emitted twice for queue songs

### ISSUE THREAD

**Issue by AlphaRyz3** [MenuDocs/erela.js#160]
When adding the first song of the queue the `trackStart` works perfectly while when like the second song of the queue starts the event gets emitted twice and idk why. 
Here's the `trackStart` event i made:
```JavaScript
manager.on("trackStart", async(player, track) => {
        nowPlaying.setDescription(`**Now playing**: ${ track.title } [${ getYoutubeLikeToDisplay(track.duration) }]`)
        await eventsChannel.send({embeds: [nowPlaying]})
    })
```

**Comment by dragonfirefox** [comment]
First, what's eventsChannel defined by? For myself it's fine.

**Comment by DelxHQ** [comment]
use `manager.once()`
