### ISSUE TITLE
Export/import playlist support

### ISSUE THREAD

**Issue by phamleduy04** [MenuDocs/erela.js#161]
erela.js don't have function for export playlist into then load it when needed.

**Comment by Spiderjockey02** [comment]
That's a very simple thing to implement, just look what values you need for Player and save to your preferred database

**Comment by phamleduy04** [comment]
i think i just need the url, but im not sure will it have a performance issue when user load a big playlist (500-1k songs maybe)

**Comment by wory48** [comment]
> i think i just need the url, but im not sure will it have a performance issue when user load a big playlist (500-1k songs maybe)

It's still fine, I've tested a spotify playlist quite 5k+ tracks, yeah, it will took a while to load, it depends on your lavalink how much it can load and ratelimit also.

**Comment by phamleduy04** [comment]
okay thank you very much
