### ISSUE TITLE
NPM ReadMe Link Issue & ReadMe Image Issue?

### ISSUE THREAD

**Issue by Grayson-code** [MenuDocs/erela.js#162]
1: The Npm Readme Contains a link to documentation and a guide that would link to some Really shady websites like shady enough for chrome to block the website completely.

While clicking on the links in Github Readme Doesn't do so Which raises some questions for me

Links =>  http://solaris.codes/projects/erelajs/docs/gettingstarted.html

2: https://i.imgur.com/wWlwXgm.png
As you see there's a bugged out image in readme which links to https://camo.githubusercontent.com/ba3ee39a0f38136b4ba395b0b0ee6a616e24a1853049ca6504f23600bae5f7f1/68747470733a2f2f736f6c617269732e636f6465732f70726f6a656374732f6572656c616a732f696d616765732f7472616e73706172656e745f6c6f676f2e706e67

So yeah Hope you guys fix it

**Comment by melike2d** [comment]
@Strandxo

**Comment by melike2d** [comment]
NPM package has been updated 👍🏼
