### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FunkiCraft** [MenuDocs/erela.js#171]
Error when trying to run Command

/home/container/node_modules/erela.js/dist/structures/Utils.js:46
            throw new RangeError("Provided argument must be present.");
                  ^
RangeError: Provided argument must be present.
    at Function.validate (/home/container/node_modules/erela.js/dist/structures/Utils.js:46:19)
    at Queue.add (/home/container/node_modules/erela.js/dist/structures/Queue.js:38:33)
    at Client.<anonymous> (/home/container/index.js:139:18)

**Comment by szymonwilczek** [comment]
Essentially, you'll find the solution in error. Either you are trying to play music (soundtrack) through the server, which is not included in your code (example: you don't have Spotify configured, and you are trying to play music through Spotify, this is just an example, don't refer to it) or the link you paste is wrong, it is not an execution output that your bot can't read.

**Comment by Anish-Shobith** [comment]
Posting error isn't enough, please also provide code if you think this error is genuinely from the library, else please use discord server for help : https://discord.gg/menudocs
