### ISSUE TITLE
Apple Music Error

### ISSUE THREAD

**Issue by Git-Jaydeep01** [MenuDocs/erela.js#174]
I used this : https://music.apple.com/in/playlist/bollywood-in-spatial-audio/pl.74a13ae85e1f48dbb4a2804bd7660cbb
It throwed me 
![image](https://user-images.githubusercontent.com/88286024/166200337-3d741b13-1e81-47c4-a9ce-604a42cdc959.png)

```
Using Discord.js V 13
erela versions  >  
    "erela.js": "^2.3.3",
    "erela.js-apple": "^1.2.6",
    "erela.js-deezer": "^1.0.7",
    "erela.js-facebook": "^1.0.4",
    "erela.js-spotify": "^1.2.0",
```

**Comment by SerenModz21** [comment]
unfortunately, this issue isn't coming from `erela.js` but instead, the `erela.js-apple` plugin, meaning u would need to report the issue to the plugin developer

from searching github for the plugin repo, it seems https://github.com/SrBatman/erela.js-apple is what ur looking for
