### ISSUE TITLE
Weird Queue Problem

### ISSUE THREAD

**Issue by fb-sean** [MenuDocs/erela.js#176]
Hello my guys before we start I dont get any erros or something like that.
I have currentlty a weird queue problem songs get added to the queue but didnt get added here a Image:

![Image](https://i.imgur.com/rK4Op3k.png)
![Image2](https://i.imgur.com/rK4Op3k.png)

The function that list this songs is this:
![Function](https://i.imgur.com/KOBz7vR.png)

The bot dont play the song too it just skips the song idk why does someone have this issue before?

**Comment by Tomato6966** [comment]
if its in the erela queue and you dont hear audio its a lavalink issue

check the lavalink logs

make sure to host lavalink with java 11 as its the most stable then

make sure to use ip routing with 1x ipv6/64 block / 25000 guilds

**Comment by fb-sean** [comment]
As you can see the Queue embed don't show the songs right that isnt a Lavalink issue xd

**Comment by Tomato6966** [comment]
ur calculation of the queue is totaly wrong too

like basic javascript please?

when u raise the number in the foor loop with i++) as the raising-condition, then why you raise it in the song index too?

```js
for(let i = 0; i< player.queue.length; i++) {
 const song = player.queue[i];
 songStrings.push(`\`#${i+1}\` [${song.title}](${song.uri)}`)
}

**Comment by Tomato6966** [comment]
so u raised the number 1 twice in 1 loop

i recommend using a map function like:-

player.queue.map((song, index) => `\`#${index+1}\` [${song.title}](${song.uri)}`)
