### ISSUE TITLE
petitio causing a lot of errors

### ISSUE THREAD

**Issue by YoYo-178** [MenuDocs/erela.js#189]
Hello, so I use erela.js with Lavalink for my discord bot and I receive a lot of errors from petitio and it even **crashes my bot everytime.**

Node.js version : v16.16.0
erela.js version : v2.3.3
Lavalink version : v3.5-rc3

```
ee [HeadersTimeoutError]: Headers Timeout Error
    at Timeout.ct [as _onTimeout] (/home/runner/what/node_modules/petitio/dist/index.js:4:5697)
    at listOnTimeout (node:internal/timers:561:11)
    at processTimers (node:internal/timers:502:7) {
  code: 'UND_ERR_HEADERS_TIMEOUT'
}
```

this is the error I receive and it's really annoying

so is there any way to fix this?

**Comment by Anish-Shobith** [comment]
#150 was merged so should be working now

Check with the latest development build
Npm: `npm install MenuDocs/erela.js#build`
Yarn: `yarn add MenuDocs/erela.js#build`

Note:
To install the development build you would require [git](https://git-scm.com/downloads) to be installed on your machine.

**Comment by ghostdevv** [comment]
The development build hasn't been updated from what I can tell

**Comment by YoYo-178** [comment]
the error still persists but it's a bit different this time
```
HeadersTimeoutError: Headers Timeout Error
    at Timeout.onParserTimeout [as _onTimeout] (/home/runner/what/node_modules/erela.js/node_modules/undici/lib/client.js:1005:28)
    at listOnTimeout (node:internal/timers:561:11)
    at processTimers (node:internal/timers:502:7) {
  code: 'UND_ERR_HEADERS_TIMEOUT'
}
```

**Comment by realpukhraj** [comment]
Same issue with me DJs v13
```js
0|main     | SyntaxError: Unexpected token  in JSON at position 0
0|main     |     at JSON.parse ()
0|main     |     at Y.json (/home/ubuntu/bot/node_modules/petitio/dist/index.js:30:574)
0|main     |     at ke.json (/home/ubuntu/bot/node_modules/petitio/dist/index.js:30:2499)
0|main     |     at runMicrotasks ()
0|main     |     at processTicksAndRejections (node:internal/process/task_queues:96:5)```

**Comment by YoYo-178** [comment]
> Same issue with me DJs v13
> 
> ```js
> 0|main     | SyntaxError: Unexpected token  in JSON at position 0
> 0|main     |     at JSON.parse ()
> 0|main     |     at Y.json (/home/ubuntu/bot/node_modules/petitio/dist/index.js:30:574)
> 0|main     |     at ke.json (/home/ubuntu/bot/node_modules/petitio/dist/index.js:30:2499)
> 0|main     |     at runMicrotasks ()
> 0|main     |     at processTicksAndRejections (node:internal/process/task_queues:96:5)```
> ```

yeah i also get this error sometimes, mostly when i use a Node.js version which is above 16

**Comment by realpukhraj** [comment]
What if you use old version of nodejs

**Comment by YoYo-178** [comment]
> What if you use old version of nodejs

it still shows up but it's less frequent

**Comment by realpukhraj** [comment]
In my case this is showing for every song request.

**Comment by birongliu** [comment]
Update to dev branch of erelajs

**Comment by YoYo-178** [comment]
> #150 was merged so should be working now
> 
> Check with the latest development build Npm: `npm install MenuDocs/erela.js#build` Yarn: `yarn add MenuDocs/erela.js#build`
> 
> Note: To install the development build you would require [git](https://git-scm.com/downloads) to be installed on your machine.

install development build via this method right?

tried already.

**Comment by YoYo-178** [comment]
> In my case this is showing for every song request.

that mostly happened to me when i used Node.js v18

**Comment by realpukhraj** [comment]
Oh I will move in shoukaku now so np for me

**Comment by YoYo-178** [comment]
> 

what Java version do you use?

**Comment by realpukhraj** [comment]
18

**Comment by YoYo-178** [comment]
> 18

I use Java 16, try using Java 16

**Comment by realpukhraj** [comment]
umm, I fixed like am changed the node and java versions for root and now it is working. But the thing is that my migration from erela to shoukaku is almost done. And shoukaku can also support v18 of node and java v18 so yeah as soon as possible migrate your bot also in shoukaku cause on the new and latest version ram and CPU usages is low.

**Comment by melike2d** [comment]
This is just an issue with your node, discord.js v14 uses undici and I doubt they would use a broken HTTP library. Shoukaku probably uses node-fetch or something that uses node's http builtin module which probably has forgiving timeouts

**Comment by YoYo-178** [comment]
> This is just an issue with your node, discord.js v14 uses undici and I doubt they would use a broken HTTP library. Shoukaku probably uses node-fetch or something that uses node's http builtin module, which probably has forgiving timeouts

nah it's with erela.js

becuase before i updated to the development build of erela.js, i was getting errors about **petitio**, and after updating to the development build i started getting errors about **undici**

**Comment by birongliu** [comment]
> > This is just an issue with your node, discord.js v14 uses undici and I doubt they would use a broken HTTP library. Shoukaku probably uses node-fetch or something that uses node's http builtin module, which probably has forgiving timeouts
> 
> 
> 
> nah it's with erela.js
> 
> 
> 
> becuase before i updated to the development build of erela.js, i was getting errors about **petitio**, and after updating to the development build i started getting errors about **undici**
> 
> 
> 
> EDIT - here's the error, it even says that it's from erela.js
> 
> ```
> 
> HeadersTimeoutError: Headers Timeout Error
> 
>     at Timeout.onParserTimeout [as _onTimeout] (/home/runner/what/node_modules/erela.js/node_modules/undici/lib/client.js:1005:28)
> 
>     at listOnTimeout (node:internal/timers:561:11)
> 
>     at processTimers (node:internal/timers:502:7) {
> 
>   code: 'UND_ERR_HEADERS_TIMEOUT'
> 
> }
> 
> ```

If you look closely it actually from undici. "/home/runner/what/node_modules/erela.js/node_modules/undici/lib/client.js:1005:28"

**Comment by melike2d** [comment]
> becuase before i updated to the development build of erela.js, i was getting errors about **petitio**, and after updating to the development build i started getting errors about **undici**

petitio uses undici...

**Comment by YoYo-178** [comment]
> > > This is just an issue with your node, discord.js v14 uses undici and I doubt they would use a broken HTTP library. Shoukaku probably uses node-fetch or something that uses node's http builtin module, which probably has forgiving timeouts
> > 
> > 
> > 
> > nah it's with erela.js
> > 
> > 
> > 
> > becuase before i updated to the development build of erela.js, i was getting errors about **petitio**, and after updating to the development build i started getting errors about **undici**
> > 
> > 
> > 
> > EDIT - here's the error, it even says that it's from erela.js
> > 
> > ```
> > 
> > HeadersTimeoutError: Headers Timeout Error
> > 
> >     at Timeout.onParserTimeout [as _onTimeout] (/home/runner/what/node_modules/erela.js/node_modules/undici/lib/client.js:1005:28)
> > 
> >     at listOnTimeout (node:internal/timers:561:11)
> > 
> >     at processTimers (node:internal/timers:502:7) {
> > 
> >   code: 'UND_ERR_HEADERS_TIMEOUT'
> > 
> > }
> > 
> > ```
> 
> If you look closely it actually from undici. "/home/runner/what/node_modules/erela.js/node_modules/undici/lib/client.js:1005:28"

yeah that's from the development build

**Comment by YoYo-178** [comment]
> > becuase before i updated to the development build of erela.js, i was getting errors about **petitio**, and after updating to the development build i started getting errors about **undici**
> 
> petitio uses undici...
> 

well dunno about that though

**Comment by Abadima** [comment]
oh my this has updated a lot, well I get `<rejected> RangeError: Plugin at index 0 does not extend Plugin.` now

**Comment by Abadima** [comment]
```js
			plugins: [
				new AppleMusic(),
				new Spotify({
					clientID,
					clientSecret
				})
			]``` my current plugins, I use `better-erela.js-spotify` and `better-erela.js-apple`

**Comment by melike2d** [comment]
I just pushed 524b5386f3102bc85ae740444b5c8c5d7258f3d6, try increasing the default headers timeout to a minute or something:

```js
client.manager = new Manager({
  nodes: [{
    poolOptions: { 
      ...
      headersTimeout: 60e3
    }
  }]
  ...
})
```

**Comment by YoYo-178** [comment]
> 

finally that fixed the issue, thank you for your time and effort.
