### ISSUE TITLE
Audio Playback issue when a new song is queued

### ISSUE THREAD

**Issue by Warrior-hound** [MenuDocs/erela.js#92]
When the new song is added to the queue the bot stops playing the current song unless the new song is played

**Comment by Anish-Shobith** [comment]
Its a simple if statement fix which was found out by `SC
#0600` 
Link to Fix: https://canary.discord.com/channels/416512197590777857/804459883017142272/827077697204650005
Server Link: https://discord.gg/menudocs

```js
    const player = client.music.create({
      guild: message.guild.id,
      textChannel: message.channel.id,
      voiceChannel: message.member.voice.channel.id
    });
    // Here we check if the player was connected before or not . If not then only we connect 
   // - player.connect();
   if (player.state !== "CONNECTED") {
   	 player.connect();
   }
```
